#version: '3.8'

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: workspace-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: workspace_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d workspace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: workspace-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: workspace-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5



  backend-django:
    build:
      context: ./backend-django
    container_name: workspace-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend-django:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  ml-fastapi:
    build:
      context: ./ml-fastapi
    container_name: workspace-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./ml-fastapi:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - rabbitmq
    # NVIDIA GPU Passthrough for your RTX 4050
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]


  frontend:
    build:
      context: ./frontend
    container_name: workspace-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
