# Generated by Django 5.0.3 on 2026-06-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_chatmessage'),
        ('core_app', '0002_chatsession_chatmessage_session'),
    ]

    operations = [
    ]
